name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: |
          cd app
          npm ci

      - name: Build
        run: |
          cd app
          npm run build

      - name: Upload pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages 
          path: app/dist

      - name: Check for symlinks in dist
        run: |
          if find app/dist -type l | grep -q .; then
            echo "Symlinks found in app/dist. Please remove all symlinks."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4